<template>
<div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>

<div>topone</div><div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>

<div>topone</div><div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>

<div>topone</div><div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>

<div>topone</div><div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>

<div>topone</div><div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>

<div>topone</div><div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>

<div>topone</div><div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div><div>topone</div><div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div><div>topone</div><div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div><div>topone</div><div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div><div>topone</div><div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div><div>topone</div><div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div><div>topone</div><div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div><div>topone</div><div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div><div>topone</div><div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div><div>topone</div><div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div><div>topone</div><div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div><div>topone</div><div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div><div>topone</div><div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div><div>topone</div><div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div><div>topone</div><div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>
<div>topone</div>

<div>topone</div>

</div>
</template>
<script>
export default {
  name: 'Home',
  components: {
    
  },
  methods:{
    goTo(path){
      this.$router.push(path) //跳转
    }
  }
}
</script>